# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('jabber', models.EmailField(max_length=30)),
                ('skype', models.CharField(max_length=30)),
                ('other_contacts', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
