# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 12:00
from __future__ import unicode_literals
from django.core.management import call_command
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    call_command('loaddata', 'initial_data.json', app_label='user_profile')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('skype', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.RunPython(forwards_func),
    ]
